spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/univ_voting
    username: postgres
    password: muskan
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
  telegram:
    bot:
      token: 8080890392:AAFP1CFLsGiKizGzducLXRUOgOn5sff3qU4

server:
  port: 8080

logging:
  level:
    root: INFO
    com.univvoting: DEBUG
